name: "Echo World Action"
description: "Prints Hello World"
author: "Your Name"

inputs:
  name:
    description: "Name to greet"
    required: false
    default: "World"

runs:
  using: "node24"
  main: "dist/index.js"
